version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: build site
          command: yarn build
      - run:
          name: chmod
          command: sudo chmod 777 ./deploy.sh
      - deploy:
          name: Deploy
          command: sh ./deploy.sh