version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "32:ae:66:b9:1c:9e:ac:a4:58:34:05:87:8a:eb:e2:e4"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: build site
          command: yarn build
      - run:
          name: chmod
          command: sudo chmod 777 ./deploy.sh
      - deploy:
          name: Deploy
          command: sh ./deploy.sh