version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: build site
          command: yarn build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages
            git config user.email "coldgust@outlook.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist dist